### ISSUE TITLE
Large log files are often impossible to open with the viewer, with or without tree virtualization

### ISSUE THREAD

**Issue by natemcmaster** [KirillOsenkov/MSBuildStructuredLog#235] opened 2019-01-28 20:34 UTC
The aspnet/AspNetCore repo produces some really large log files, like 100 MB or bigger. I've had trouble working with these because this viewer doesn't handle large log files of this size. As a workaround, I usually end up replaying them to a text file and using Sublime Text to search through them...which is _super_ fun.

The "Enable tree virtualization" option saves a lot of memory usage, but the UI consistently freezes when opening logs >30 MB.
On the other hand, if disable tree virtualization, the viewer can end up using several GB of memory.

Any suggestions on how we might be able to improve perf? I'd be happy to provide log files and memory dumps if that would help.

**Comment by KirillOsenkov** [comment] 2019-01-28 21:33
Yes send me the .binlogs and I can see what I can do. Unfortunately you'll want virtualization off, this is why the viewer is 64-bit. It's already highly optimized so I'm not sure what else I'll be able to squeeze out.

Is the initial load time too long or subsequent working with the UI?

**Comment by natemcmaster** [comment] 2019-01-28 23:42
The dumps are logs are too big for GitHub, so I'll send you email internally with a network share.

Here is what I did to create the log:
1. Clone https://github.com/aspnet/AspNetCore
2. Run `restore.cmd /bl`

The binlog is 46 MB. 

- With tree virtualization: it consistently freezes after browsing the tree for 10-20 seconds. Memory usage is usually ~700mb
- Without: it doesn't freeze, but it will use more and more memory as I begin to browse the log, sometimes as high as 4-5 GB of memory.

**Comment by natemcmaster** [comment] 2019-01-28 23:44
> Is the initial load time too long or subsequent working with the UI?

Initial load time is usually fine. For a 46 mb file, initial load is about 15 seconds. Some of our complete builds will have logs that are 200+ MB, and load time there can exceed a minute.

**Comment by ericstj** [comment] 2019-03-13 22:41
@Eilon this is what we were discussing in today's meeting.

We see similar problems for CoreFx full stack builds.  I thought I found a place where you were hitting a zip issue but on closer inspection it shouldn't be the case.

It sounds like memory usage is more for the visual tree rather than the logs themselves.  Perhaps a UI redesign (or a different UI mode) that doesn't require a tree-view?  Something that lets you push into layers in stack and pop those off so that you don't have to visualize everything at once?

Another thing to consider would be to have this target .NETCore 3.0 and run on the new WPF where folks can start looking at making some improvements.

**Comment by KirillOsenkov** [comment] 2019-03-14 02:16
Yes, after .NET Core 3.0 RTMs I'm planning to move to the new WPF and investigate the hang in the virtualized tree view. Here's the issue tracking that: https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/21

When the tree view is virtualized performance and memory consumption should be much better.

Sam Bent from the WPF team sent me detailed guidance on how to collect data for the repro, however it's involved and I didn't have time to investigate thoroughly.

Other than that, I won't have time to investigate more scalable UI approaches in the near future. I do encourage the community to prototype various approaches and see what is viable. This codebase should provide a solid foundation for such experiments and you're unlikely to find a better suited framework than WPF (or Avalonia). .binlog is a simple raw format to work with, so you could read the records and do whatever you want with them. 

Maybe some high performance in-memory database with a powerful query engine is a solution. I imagine you could just write queries and browse results a-la LinqPad. Or explore the tree one level at a time, with the ability to go up or drill down into children. The possibilities are endless! For now I'm leaving this as an exercise to the reader :)

**Comment by Eilon** [comment] 2019-03-14 16:58
@KirillOsenkov - hello from the ASP.NET team. If I can get a group of people to try to solve this hack-a-thon style, would that work for you? Seems like you're pretty open to this.

**Comment by KirillOsenkov** [comment] 2019-03-14 17:01
@Eilon I could be available to walk people through the codebase and answer questions! I can't commit to more than a couple hours at a time though.

**Comment by tmat** [comment] 2019-09-08 22:05
Even when a large binlog can be opened it's often hard to navigate. Would it make sense to add a project based view? That is, start with just a list (or a graph) of all projects with a search box. Find and select a project of interest and display the build tree of just that project (all targets executed in the project).

**Comment by tmat** [comment] 2019-09-09 16:22
@stephentoub This is gonna be a problem when we merge multiple already large repos.

**Comment by stephentoub** [comment] 2019-09-09 17:06
> This is gonna be a problem when we merge multiple already large repos.

We already support building portions in the existing repos, e.g. you can build just System.Collections.Concurrent. That's not going to change.

**Comment by tmat** [comment] 2019-09-09 17:07
@stephentoub This is not about building locally, but building on CI - CI builds all projects into a single binlog.

**Comment by stephentoub** [comment] 2019-09-09 17:08
Are you saying then that corefx for example isn't too large but corefx+coreclr is?

**Comment by tmat** [comment] 2019-09-09 17:10
Possibly. I know that ASP.NET already produces binlog that's 500MB and the viewer is not able to open that. So this might be a problem elsewhere.

**Comment by japj** [comment] 2019-09-20 14:33
Just as another idea, would it be possible for the MSBuild taskt to split off logging into seperate binlog files to prevent files to get too big?

**Comment by KirillOsenkov** [comment] 2019-09-20 16:10
I think the problem is in the viewer, it should just handle large logs. binlog recording is fine. 

I’ll think of something, just need the time.

**Comment by KirillOsenkov** [comment] 2021-05-14 20:42
Binlog size has been fixed in 16.10 Preview 3.

Hanging UI has been fixed in WPF in a Windows update. The tree view can now be virtualized (so check that Virtualize checkbox on the start screen).

Binlog loading times have been optimized as well.

I'll think about a mode of starting with a list of projects and then displaying a separate tree just for that project, but it's highly non-trivial. I'll file a separate issue for that.

**Closed by KirillOsenkov** 2021-05-14 20:42 UTC
Labels: high pri
