### ISSUE TITLE
Add support for dotnet msbuild

### ISSUE THREAD

**Issue by m0sa** [KirillOsenkov/MSBuildStructuredLog#57] opened 2017-04-11 20:32 UTC
The dotnet CLI tools enable us to call msbuild via the `dotnet msbuild ...` command. Currently it's not possible to attach the structured logger to such a msbuild run, it fails with the following error:

```
dotnet msbuild Some.sln /v:diag /nologo /logger:StructuredLogger,"C:\Users\SomeUser\AppData\Local\MSBuildStructuredLogViewer\app-1.0.130\StructuredLogger.dll";"C:\Users\SomeUser\Desktop\structuredlog.buildlog"
MSBUILD : error MSB1021: Cannot create an instance of the logger. Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

**Comment by KirillOsenkov** [comment] 2017-04-11 20:42
dotnet CLI uses CoreCLR so we need a .NET Standard version of StructuredLogger.dll not the .NET Framework (Desktop) version. 

Try downloading this NuGet package: https://www.nuget.org/packages/Microsoft.Build.Logging.StructuredLogger/1.0.130
and inside it there's the `lib\netstandard1.5\StructuredLogger.dll`. Try passing that to `dotnet build` instead of the one you've been passing (the desktop one).

**Comment by m0sa** [comment] 2017-04-11 21:50
Great! Any chance to add that as an option in the GUI?

![image](https://cloud.githubusercontent.com/assets/503702/24932376/94c443ae-1f11-11e7-9b98-1ceb59d5f4e8.png)

**Comment by dsplaisted** [comment] 2017-04-13 04:55
What are the tradeoffs between using the custom structured logger and the new `/bl` option that's built into MSBuild now?

**Comment by KirillOsenkov** [comment] 2017-04-13 16:53
BinaryLogger (/bl) will consume less memory and hopefully not OOM on huge builds, whereas the StructuredLogger .buildlog format may OOM on large builds (by design). The /bl .binlog format is streaming and should be constant in terms of memory.

StructuredLogger on the other hand captures the target graph so it is able to show DependsOn list for each target and also order targets slightly better in some cases.

Also StructuredLogger is much more compact since it is not streaming and thus able to use string deduplication, reducing the log file up to 10x smaller as a .binlog for a Binary Logger.

BinaryLogger is replayable and you're able to reconstruct text logs of any verbosity out of it. It is hard to reconstruct text logs of conventional format from a StructuredLogger log.

Other than that they're pretty much equivalent.

**Comment by KirillOsenkov** [comment] 2017-04-13 17:02
@m0sa how exactly would you like to see dotnet msbuild to be integrated into the UI? Can you make a mockup in MSPaint? I'm not sure I am well familiar with dotnet msbuild and so I don't have a clear idea of how that choice would look to the user. Thanks!

**Comment by KirillOsenkov** [comment] 2017-06-16 06:58
I'm going to close this as fixed, but please feel free to reopen or open a new one if you feel there's something else I can help with.

**Closed by KirillOsenkov** 2017-06-16 06:58 UTC
