### ISSUE TITLE
WPF's inner build (wpftmp.csproj) preprocess view lies

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#273] opened 2019-11-15 03:45 UTC
Given a WPF project such as:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp5.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.1.13-beta">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

Where `MainWindow.xaml.cs` includes the line:

```cs
Title = ThisAssembly.AssemblyFileVersion;
```

A build error follows. This is because of https://github.com/NuGet/Home/issues/5894, which is beside the point. The point is, in investigating the failure, I use the `/bl` switch and load the file into msbuild structured log viewer. I then find the wpftmp.csproj and click the Preprocess command on it, which shows me this:

![image](https://user-images.githubusercontent.com/3548/68915481-77973400-071f-11ea-8771-887f07fd403f.png)

From this screenshot you'll see that nerdbank.gitversioning.targets have been imported. But in fact, I don't believe they have, since it it was imported there would not be a build failure. Also the side effects of having imported it such as influence on project properties would be visible in the evaluation model which the Properties tree within the structured log viewer does not show are present.
Finally, when I run `msbuild WpfApp3_meucdeke_wpftmp.csproj /p:_TargetAssemblyProjectName=WpfApp3,IntermediateOutputPath=obj\Debug\netcoreapp5.0\,AssemblyName=WpfApp3 /pp:out.xml` myself and inspect the `out.xml` file, there's no trace of the nerdbank.gitversioning.targets file having been imported.

**Comment by KirillOsenkov** [comment] 2019-11-15 04:04
Mind sharing the .binlog with me? E-mail or `\\kirillo2\Incoming`

Search for `$import nerdbank` and `$noimport nerdbank` to determine exactly whether a file was imported or not.

**Comment by KirillOsenkov** [comment] 2019-11-15 04:09
Never mind; I reproduced. Investigating.

**Comment by KirillOsenkov** [comment] 2019-11-15 04:15
Aha, OK, the full project imported the NuGet generated targets just fine:
![image](https://user-images.githubusercontent.com/679326/68916527-3f8df200-071b-11ea-82f9-452274881cfc.png)

but the tmp proj didn't:
![image](https://user-images.githubusercontent.com/679326/68916547-5a606680-071b-11ea-87ca-56c5e61ac53b.png)

**Comment by KirillOsenkov** [comment] 2019-11-15 04:21
Hmm, this very well may be a bug in the viewer (I can imagine I could be grabbing the $import event args from the "full" project instead of the "wpftmp" project), but I can't repro this:

![image](https://user-images.githubusercontent.com/679326/68916762-3ea99000-071c-11ea-91f3-f11434cc35b7.png)

This behavior also doesn't seem right, but it's different from what you're seeing. 

What version of the viewer do you have? Can you start it from the Start Menu and let it auto-update to 2.0.152?

**Comment by KirillOsenkov** [comment] 2019-11-15 04:26
OK yes this is certainly a bug. My logic for stitching imports together is very naive and doesn't take into account that there may be multiple evaluations for the same project that are different.

**Comment by AArnott** [comment] 2019-11-15 04:33
Thanks for looking.

FYI I was on 2.0.112.

**Comment by KirillOsenkov** [comment] 2019-11-15 06:02
Hey @AArnott thanks for reporting!

Would you be willing to get the latest source for the viewer, build the viewer from source and try it out? Here's the commit which I think should fix the issue:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/17d1efbab4777704496fc57961e72d02b0ad48aa

If you preprocess the main project you should see the nuget targets imported, but if you preprocess wpftmp you shouldn't see it.

I can't test it myself due to https://github.com/microsoft/msbuild/issues/4714 and I also don't have dotnetcore 5.0

**Comment by AArnott** [comment] 2019-11-15 06:22
Sure. I'll try. Netcoreapp5.0 isn't important though. It happens on 3.0 too.

**Comment by KirillOsenkov** [comment] 2019-11-15 19:31
I've published 2.0.159 that I hope will fix the issue for the most part.

It will still not be completely accurate because the same project can be evaluated more than once with different sets of imports. But now at least we won't be conflating evaluations from two different projects (such as .csproj and .wpftmp.csproj) so the particular bug you've reported should be fixed now.

I don't think MSBuild currently gives me a way to associate a project with its evaluation so I don't know which evaluation to pick when stitching imports together for a project. Perhaps I should open an MSBuild bug.

Thanks again for alerting me to this.

**Comment by KirillOsenkov** [comment] 2019-11-15 19:44
I filed https://github.com/microsoft/msbuild/issues/4926

**Comment by KirillOsenkov** [comment] 2020-09-05 05:04
This should be further improved by https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/aa83ca34424c3c87bcd4fdda43cd443b24310749

**Closed** 2020-09-05 05:05 UTC
