### ISSUE TITLE
The log does not contain information about items being removed

### ISSUE THREAD

**Issue by atanasa** [KirillOsenkov/MSBuildStructuredLog#113] opened 2017-08-24 13:17 UTC
The binary and structured log does not contains information about msbuild items that are being removed. 
E.g. the result of `<Reference Remove="%(_ReferencesFromNuGetPackages.FileName)" />` is not shown in the log.

**Comment by KirillOsenkov** [comment] 2017-08-24 18:06
Currently this is by design, as MSBuild doesn't record mutations of items that happen during the evaluation. If an item is modified when a target is building, it will be logged. MSBuild does log all final items for each project after evaluation is complete, just not the mutations that happen during the evaluation.

I'm going to close this bug because it's not related to logger or viewer, but rather an aspect of MSBuild itself (specifically the evaluator). I've filed an issue https://github.com/Microsoft/msbuild/issues/2469 to discuss that.

Thanks.

**Closed by KirillOsenkov** 2017-08-24 18:06 UTC
