### ISSUE TITLE
WPF VirtualizingStackPanel: System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by surajraja** [KirillOsenkov/MSBuildStructuredLog#665] opened 2023-03-21 17:00 UTC
---------------------------

---------------------------
Unexpected exception. Sorry about that.
Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new

System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by KirillOsenkov** [comment] 2023-03-21 17:01
oh wow, thanks for logging.

**Comment by KirillOsenkov** [comment] 2023-03-26 22:23
I'm not sure what to do about this. It's a bug in WPF and it won't be fixed. Hopefully this is infrequent enough that we can just ignore.

If this continues, try turning off virtualization:

![image](https://user-images.githubusercontent.com/679326/227808389-66202292-72ea-440d-9ae6-d0f234810682.png)

**Comment by KirillOsenkov** [comment] 2023-11-09 00:49
Duplicate of #570

**Closed by KirillOsenkov** 2023-11-09 00:49 UTC
Labels: WPF
