### ISSUE TITLE
detect rebuild problems?

### ISSUE THREAD

**Issue by Trass3r** [KirillOsenkov/MSBuildStructuredLog#25] opened 2016-06-06 08:50 UTC
Is it possible to highlight issues leading to more rebuilds than necessary?
A prime example is a C++ project with a header file that does not exist on disc.
But in a mixed (C#, managed C++) solution there are other causes we couldn't figure out yet.

**Comment by KirillOsenkov** [comment] 2016-06-08 05:20
For now the cheapest way is to search for "Building target completely".

Longer term I hope to add more smart analytics to determine a root cause that causes cascading unnecessary rebuilds.

**Comment by KirillOsenkov** [comment] 2017-11-24 19:02
I'm going to close this for now because I don't have any more concrete ideas, but if something constructive comes up we can always consider it again.

**Closed by KirillOsenkov** 2017-11-24 19:02 UTC
Labels: question
