### ISSUE TITLE
ArgumentNullException in MS.Internal.Media.VisualTreeUtils.AsNonNullVisual

### ISSUE THREAD

**Issue by chsienki** [KirillOsenkov/MSBuildStructuredLog#611] opened 2022-07-14 03:23 UTC
Looking at binlog https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvOWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkL2J1aWxkSWQvMTg3ODY3MC9hcnRpZmFjdE5hbWUvQnVpbGRMb2dzX1NvdXJjZUJ1aWxkX01hbmFnZWRfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog

![image](https://user-images.githubusercontent.com/16246502/178891166-1f1efbda-5961-446b-9d71-dce14718024c.png)

When the tree in the center panel is scrolled off screen horizontally, attempting to scroll vertically results in the following stack traces popping up.

Looks like maybe an internal WPF bug, but figured I'd open an issue here just in case?

```
System.ArgumentNullException: Value cannot be null.

Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Controls.VirtualizingStackPanel.SetAnchorInformation(Boolean isHorizontalOffset)
   at System.Windows.Controls.VirtualizingStackPanel.<>c__DisplayClass94_0.<InitializeViewport>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

```
System.ArgumentNullException: Value cannot be null.

Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Controls.VirtualizingStackPanel.SetAnchorInformation(Boolean isHorizontalOffset)
   at System.Windows.Controls.VirtualizingStackPanel.SetVerticalOffsetImpl(Double offset, Boolean setAnchorInformation)
   at System.Windows.Controls.ScrollViewer.OnMouseWheel(MouseWheelEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by KirillOsenkov** [comment] 2022-10-06 19:28
This is likely a WPF bug, so we have no control over it. And Sam Bent, the WPF expert on VirtualizingStackPanel has recently left Microsoft, so we're stuck with it I'm afraid.

**Comment by KirillOsenkov** [comment] 2023-11-09 00:51
Duplicate of #570

**Closed** 2023-11-09 00:52 UTC
Labels: WPF
