### ISSUE TITLE
ArgumentNullException Parameter name: element (VisualTreeUtils.AsNonNullVisual)

### ISSUE THREAD

**Issue by JustinSchneiderPBI** [KirillOsenkov/MSBuildStructuredLog#623] opened 2022-10-04 06:10 UTC
Unexpected exception. Sorry about that.
Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new

System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by KirillOsenkov** [comment] 2023-11-09 00:49
Duplicate of #570

**Closed by KirillOsenkov** 2023-11-09 00:49 UTC
Labels: WPF
